#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-desktop
    username: testing
    password: $6$rounds=4096$1354872853$7QKw5DoXiEhIC2EMVzyCu1mAR8K349qAZa2JkOMMkN07ely6/hTBEl8IL6iNU6rMXQqAafhzvWtS6nTIrgil91
  keyboard:
    layout: be
    variant: nodeadkeys  # Belgian (Period) keyboard
  locale: en_US.UTF-8  # English as the main language
  timezone: Europe/Brussels  # Belgian timezone
  storage:
    layout:
      name: lvm
  user-data:
    users:
      - name: testing
        sudo: ALL=(ALL) NOPASSWD:ALL
  network:
    ethernets:
      enp0s3:
        dhcp4: true
    version: 2
