autoinstall:
  identity:
    hostname: p190204.vito.local
    password: $6$rounds=4096$1354872853$fISud9WCKd7ZcOgcsJ1Z/dP.KFqyCtyTjaeioevGDVKT2T/wJmrHGLd807pReTIJLmReUhhIcYEqbOQr2a0kC.
    username: testing
  keyboard:
    layout: us
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      enp0s3:
        dhcp4: true
    version: 2
  storage:
    config:
      grub_device: true
      id: 0
      match:
        size: largest
      name: ''
      partitions:
      - flag: bios_grub
        id: 0
        size: 1MB
        type: partition
      - flag: lvm
        id: 1
        size: 100%
        type: partition
      preserve: false
      ptable: gpt
      type: disk
      wipe: superblock-recursive
    layout:
      name: lvm
  timezone: Europe/Brussels
  user-data:
    users:
    - name: testing
      sudo: ALL=(ALL) NOPASSWD:ALL
  version: 1
